name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Build Docker image
      run: |
        docker build -f Dockerfile -t chatapp-image .

    - name: Install Render CLI
      run: |
        curl -sSL https://render.com/cli/install | bash
        sudo mv render /usr/local/bin

    - name: Log in to Render
      run: |
        echo "${{ secrets.RENDER_API_KEY }}" | render login --api-key

    - name: Deploy to Render
      run: |
        render deploy --docker --service-name chatapp-render-app-name --region us --image chatapp-image
