name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Docker Image
      run: |
        docker build -f .github/workflows/Dockerfile -t chatapp-image .
    - name: Login to Heroku
      uses: akshnz/heroku-login-action@v1
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    - name: Deploy to Heroku
      run: |
        heroku container:login
        heroku create chatapp-heroku-app-name --region us
        heroku container:push web --app chatapp-heroku-app-name
        heroku container:release web --app chatapp-heroku-app-name
